version: "3.7"

services:
  database_academia:
    image: postgres
    container_name: database_academia
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=academia
      - POSTGRES_DB=academia
    volumes:
      - pgdata:/data/postgres
    network_mode: host
  app:
    build: .
    container_name: academia
    ports:
      - 4000:4000
    volumes:
      - .:/usr/app
    network_mode: host


volumes:
  pgdata:
    driver: local